---
- name: Configure Jenkins in the virtual machine
  hosts: jenkins_server
  become: true
  vars:
    java_packages: "openjdk-21-jdk"
    jenkins_packages: "jenkins"
  tasks:
    - include_tasks: common_jenkins_tasks.yml
    - name: Install Jenkins
      apt:
        name: "{{ jenkins_packages }}"
        state: present
    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
    - name: Wait for Jenkins to be fully up and running
      wait_for:
        port: 8080
        delay: 10
        timeout: 300
    - name: Get initial admin password
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: initial_admin_password
      changed_when: false
    - name: Print initial admin password
      debug:
        msg: "The initial admin password is: {{ initial_admin_password.stdout }}"